version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./lekkerreact
    ports:
      - "3050:3000"
  achterkant:
    build:
      dockerfile: Dockerfile.dev
      context: ./deachterkant
    ports:
      - "5050:5050"